

let pagesPlay = {
	state:{
		message:{
			friends:[
				
			],
			//第一段内容
			friendsOne:[
				{
					type:0,
					value:'学长好！终于等到你了！<br/>我就知道没有东西可以难倒你！'
				},
				{
					type:1,
					value:'说起来这个软件还挺难用，添加个好友，都要大费周章。'
				},
				{
					type:0,
					value:'没有办法，我很怕被监听到，所以才设置这么多障碍。'
				},
				{
					type:0,
					value:'我一直很担心，教授的失踪会不会与前几年的<text style="color:red">科学家集体自杀事件</text>有关。',
					isCt:'    2006年，粒子对撞实验出现了种种匪夷所思的结果，13位物理学界最前沿的科学家相继自杀。经有关调查记载，大部分科学家死前都曾留下类似“物理学从来就不存在”的遗言，而他们中的大部分都有参加一个名叫“科学边界”的组织。'
				},
				{
					type:1,
					value:'呃，不会...'
				},
				{
					type:1,
					value:'虽然那件事让我们都受到巨大的打击，但是我确定教授已经走出来了。至于我……我虽然放弃了物理学的研究工作，不过……总之，我们不至于脆弱到直接自杀。'
				},
				{
					type:0,
					value:'但是当年到底发生了什么，为什么会集体自杀呢？'
				},
				{
					type:1,
					value:'Emmm，这很难解释，你还是不要知道为好。'
				},
				{
					type:0,
					value:'但这个问题会一直困扰着我，还是告诉我吧，我相信，我一定可以接受的.'
				},
				{
					type:1,
					value:'...，好吧，还记得老师笔记中的那张图片嘛.'
				},
				{
					type:1,
					value:'img',
					img:require('../static/img/playPassword/zc.jpg'),
				},
				{
					type:1,
					value:'这是老师在笔记中，看似随意画的内容，却蕴藏着让人深思的问题。'
				},
				{
					type:1,
					value:'一张台球桌上的6个球，假设六个人同时击球，会发生什么？'
				},
				{
					type:0,
					value:'唔……这些球的路径，图案看上去就像是几个英文字母。可到底是什么呢？',
					isEnd:1
				}
			],
			//第二段内容，需要答对了追加,根据上面生成id
			friendsTwo:[
				{
					type:1,
					value:'KVAX，对，是这样，没错.'
				},
				{
					type:0,
					value:'可...这和这件事有什么关系呢？'
				},
				{
					type:1,
					value:'假如在房间的不同时间不同地点重复这个实验，你觉得结果会是怎样的？'
				},
				{
					type:0,
					value:'结果……结果肯定是一样的啊。因为这是基础物理学规律啊。'
				},
				{
					type:1,
					value:'没错，这是物理学规律，而且说明物理规律在时间空间上是均匀的，这是一切物理的基础。'
				},
				{
					type:0,
					value:'别卖关子了，学长。可这个究竟说明了什么？'
				},
				{
					type:1,
					value:'假如你想象另外一种结果，1号球被撞入洞内，2好球走偏了，3号求飞上了天花板，4号球像一个受惊的麻雀在房间里乱飞，5号球跳进了你的口袋，6号球以光速飞出击穿了墙壁，然后飞出了地球太阳系，你会怎么想？'
				},
				{
					type:0,
					value:'？？？这...这种情况，真的发生了嘛？'
				},
				{
					type:1,
					value:'发生了，近几年有三台昂贵的“台球桌”被造了出来。这三台粒子对撞机的实验出了问题，在一切条件相同的情况下，出来的实验数据却毫无规律。科学家慌了，他们一次次实验，得到一次次毫无规律毫无意义的数据。'
				},
				{
					type:0,
					value:'这……这意味着……'
				},
				{
					type:1,
					value:'这意味着物理规律在时间和空间上的不均匀。'
				},
				{
					type:0,
					value:'？？？如果是这样的话，我突然无法理解这一切将会意味着什么。'
				},
				{
					type:1,
					value:'你仔细想想，以你的聪明也一定推论得出来。'
				},
				{
					type:0,
					value:'这意味着基础物理，不，是物理规律不存在，这太可怕了……物理学不存在，这对前沿理论探索者来说是灾难性的。'
				},
				{
					type:0,
					value:'可实验结果和科学家信仰有什么联系呢？'
				},
				{
					type:1,
					value:'嗯.简单点来说吧,我给你举个例子.你知道<text style="color:red">神射手理论</text>嘛？'
					
				},
				{
					type:0,
					value:'以前好像有听说过,那是什么？'
				},
				{
					type:1,
					value:'img',
					img:require('../static/img/playPassword/sss.jpg'),
				},
				{
					type:1,
					value:'能猜出神射手分别将子弹打入了哪些网格之中了么？',
					isEnd:2
				}	
			],
			friendsThree:[
				{
					type:0,
					value:'这并没有什么难度啊，可这说明了什么呢？',	
				},
				{
					type:1,
					value:'神射手理论，嗯.怎么说呢...'
				},
				{
					type:1,
					value:'有一名神枪手，在一个靶子上，每隔10cm打出一个洞。设想靶子上生活着一种二维智生物，它们中的科学家在对自己的宇宙进行观察后，发现了一个伟大的定律：每隔10cm单位，必然会有一个洞。 它们把这个神枪手一时兴起的随意行为，看成自己宇宙的铁律。'
				},
				{
					type:0,
					value:'这也太……</br>这些二维生物也太可笑了，不过也有点悲哀。'
				},
				{
					type:1,
					value:'同样的，在老师的笔记中还有这样一张图片不知道你有没有留意到.'
				},
				{
					type:1,
					value:'img',
					img:require('../static/img/playPassword/ncj.jpg'),
				},
				{
					type:0,
					value:'我还记得，可我不确定老师究竟想说什么？'
				},
				{
					type:1,
					value:'这是火鸡与农场主理论.'
				},
				{
					type:0,
					value:'这真的是科学理论么，这些名字都好有趣。'
				},
				{
					type:1,
					value:'嗯，有时候科学家就是这么简单粗暴，不，是简单明了。'
				},
				{
					type:1,
					value:'那么现在我问你一个问题，根据图片的提示，第六天每只火鸡能分配米粒数字是多少?'
				},
				{
					type:0,
					value:'嗯，让我想想，学长，还是你告诉我吧。我现在脑子有点懵懵的.',
					isEnd:3
				}
			],
			friendsFour:[
				{
					type:1,
					value:'56颗米'
				},
				{
					type:0,
					value:'可我还是不太理解，到底火鸡与农场主理论代表着什么？'
				},
				{
					type:1,
					value:'在火鸡的世界中，他们的学者发现每天上午11点就会有食物降临，他们还计算了不同日期的食物的规律。正在他们准备向其他人公布这个消息，更好得分配储藏这些食物的时候，感恩节降临了。'
				},
				{
					type:0,
					value:'突然很同情感恩节的火鸡……'
				},
				{
					type:0,
					value:'我想我可能明白了他们自杀的原因，你的意思是说我们就像火鸡或者二维生物，在我们之外有更恐怖的力量随意玩弄我们？'
				},
				{
					type:0,
					value:'科学家们因为自己研究的物理学被控制，甚至不存在而信仰崩塌。但我还是很难相信，什么样的力量能造成这种现象？ '
				},
				{
					type:1,
					value:'目前我也不知道，只能等待……'
				},
				{
					type:0,
					value:'那教授会不会出事？'
				},
				{
					type:1,
					value:'我不确定教授现在在哪里，但我知道他不会因为那件事消沉甚至失去信仰。他的失踪一定还有一些其他原因。'
				},
				{
					type:0,
					value:'我现在渐渐能理解那些人了，在将自己的全部都献给了科学之后，一心只是为了造福人类，为了更美好的将来，他们抛开了自我的得失，下了所有的赌注，结果现实跟他们开了一个天大的玩笑。'	
				},
				{
					type:1,
					value:'相比于他们，我真的觉得有些惭愧，我并没有像他们那样虔诚的信仰科学。'
				},
				{
					type:0,
					value:'而我选择这条路，也只是兴趣使然，科学对我来说一直像是童话般绚丽，是一种美好的向往。'
				},
				{
					type:1,
					value:'虽然如此，但我觉得这也让我更好的从另一个视角去审视，而不是悲观的接受一切。我觉得，真相可能并不全然是我们看到的那些。'
				},
				{
					type:0,
					value:'你是说？难道有人，哦不，有超出人所能想象的力量，能够左右我们的科学？'
				},
				{
					type:1,
					value:'也许现在的我们鼠目寸光，在真相面前我们显得格外渺小，但也并不是所有人都放弃了希望和信仰，一定还有人会坚持在真理的道路上一直走下去。'
				},
				{
					type:0,
					value:'你似乎说的很有道理，我们不该放弃希望……对了！'
				},
				{
					type:0,
					value:'我差点忘了正事，我们还要寻找教授的下落！那些警察似乎并不关心教授的死活，他们好像在找什么东西。以教授的性格，他应该在这些物品中留下了线索，我们一起各自寻找，如果有新的发现就还是通过这个软件沟通。'
				},
				{
					type:1,
					value:'好的，我会根据你给我的东西搜寻一些线索，设法找到教授。',
					isEnding:1
				}
			],
			chat:{
				active:0
			}
		}
	},
	mutations:{
		addFrinend(state,obj){
			let flag = state.message.friends.some(item=> item.name ==obj.name)
			if(flag){
				
			}else{
				state.message.friends.push(obj)
			}
		},
		resetFrinend(state,arr){
			state.message.friends = arr
		},
		updeteFrinend(state,obj){
			let index = state.message.friends.findIndex(item=> item.name ==obj.name)
			   state.message.friends[index].contacts.push(obj.obj)
		},
		concatFrinend(state,obj){
			let index = state.message.friends.findIndex(item=> item.name ==obj.name)
			 state.message.friends[index].contacts = [...state.message.friends[index].contacts,...obj.arr]			
		},
		updeteChatActive(state,num){
			state.message.chat.active = num
		}
	}
}




export default pagesPlay 